# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.SlugField(default="default", max_length=64, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "site",
                    models.ForeignKey(
                        default="default",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="blog.site",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GameMap",
            fields=[
                ("id", models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps",
                        to="blog.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "map",
                "verbose_name_plural": "maps",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="blog.gamemap",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("icon", models.CharField(max_length=64)),
                ("enabled_by_default", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="blog.item",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("map", "slug"),
                name="uniq_category_per_map",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("category", "slug"),
                name="uniq_item_per_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="marker",
            constraint=models.UniqueConstraint(
                fields=("item", "slug"),
                name="uniq_marker_per_item",
            ),
        ),
    ]
