# Generated by Django 6.0.2 on 2026-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_map_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='image_file',
            field=models.FileField(blank=True, help_text='Upload a map image (SVG, PNG, JPG, or WebP).', upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='image',
            field=models.CharField(blank=True, help_text='Public image path used by the map viewer, e.g. /maps/palpagos.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(choices=[('travel', 'Travel'), ('tower', 'Tower'), ('alpha', 'Alpha'), ('dungeon', 'Dungeon'), ('chest', 'Chest'), ('element', 'Element'), ('fruit', 'Fruit'), ('note', 'Note'), ('statue-alt', 'Statue'), ('grace', 'Grace'), ('boss', 'Boss'), ('merchant', 'Merchant'), ('seed', 'Seed'), ('tear', 'Tear')], default='travel', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='marker',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
    ]
