# Generated by Django 6.0.2 on 2026-09-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameMaps',
            fields=[
                ('Map_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=200)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('GameName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='blog.games')),
            ],
            options={
                'verbose_name_plural': 'Game Maps',
            },
        ),
        migrations.CreateModel(
            name='ItemsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('GameName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='blog.games')),
            ],
            options={
                'verbose_name_plural': 'Items Categories',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=100)),
                ('x_location', models.IntegerField()),
                ('y_location', models.IntegerField()),
                ('GameName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='blog.games')),
                ('CategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='blog.itemscategories')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemsSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryName', models.CharField(max_length=100)),
                ('GameName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_subcategories', to='blog.games')),
            ],
            options={
                'verbose_name_plural': 'Items SubCategories',
            },
        ),
        migrations.AddConstraint(
            model_name='itemscategories',
            constraint=models.UniqueConstraint(fields=('CategoryName', 'GameName'), name='unique_category_per_game'),
        ),
        migrations.AddConstraint(
            model_name='itemssubcategories',
            constraint=models.UniqueConstraint(fields=('SubCategoryName', 'GameName'), name='unique_subcategory_per_game'),
        ),
    ]
