# Generated by Django 6.0.2 on 2026-09-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemssubcategories',
            name='unique_subcategory_per_game',
        ),
        migrations.AddField(
            model_name='itemssubcategories',
            name='PrimalCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_subcategories', to='blog.itemscategories'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='itemssubcategories',
            constraint=models.UniqueConstraint(fields=('SubCategoryName', 'GameName', 'PrimalCategory'), name='unique_subcategory_per_game'),
        ),
    ]
