# Generated by Django 6.0.2 on 2026-09-12 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Games'},
        ),
        migrations.CreateModel(
            name='GameMaps',
            fields=[
                ('Map_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('GameName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='blog.games')),
            ],
            options={
                'verbose_name_plural': 'Game Maps',
            },
        ),
    ]
