# Generated by Django 6.0.2 on 2026-09-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_games_options_gamemaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemaps',
            name='height',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='gamemaps',
            name='image_path',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemaps',
            name='width',
            field=models.IntegerField(default=1920),
        ),
    ]
