# Generated by Django 6.0.2 on 2026-09-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_itemssubcategories_unique_subcategory_per_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='SubCategoryName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='blog.itemssubcategories'),
            preserve_default=False,
        ),
    ]
