# Generated by Django 6.0.2 on 2026-09-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_items_subcategoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemaps',
            name='coordinates_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemaps',
            name='origin_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamemaps',
            name='origin_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamemaps',
            name='pixels_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
