# Generated by Django 6.0.2 on 2026-09-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_gamemaps_coordinates_feature_gamemaps_origin_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
