# Generated by Django 6.0.2 on 2026-09-16 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_games_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Unique_token',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
