# Generated by Django 6.0.2 on 2026-09-16 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_items_unique_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='icon',
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='itemssubcategories',
            name='Default_icon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
