# Generated by Django 6.0.2 on 2026-09-18 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_items_icon_itemssubcategories_default_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="icon",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                max_length=200,
                null=True,
            ),
        ),
    ]
