# Generated by Django 6.0.2 on 2026-09-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Games',
        ),
    ]
