# Generated by Django 6.0.2 on 2026-09-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_game_games'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['name'], 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='maps/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='blog.games')),
            ],
            options={
                'verbose_name': 'map',
                'verbose_name_plural': 'maps',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blog.gamemap')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x', models.FloatField(default=50)),
                ('y', models.FloatField(default=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='blog.item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='gamemap',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='uniq_map_per_game'),
        ),
    ]
